### PR TITLE
adds an announcement bar

### PR DESCRIPTION
**Pull request by banukutlu**
#331

### CODE REVIEW

**Review by cdmo — CHANGES_REQUESTED** [review]
The default state of this feature is a blank white bar at the top of the page. Is that intentional? Thinking we should either set it as false or provide a default that works without configuration?

**Comment by banukutlu** [comment]
> The default state of this feature is a blank white bar at the top of the page. Is that intentional? Thinking we should either set it as false or provide a default that works without configuration?

I was thinking I had it set as false, my mistake, will fix

**Review by cdmo — APPROVED** [review]
Maybe an example in the readme would help too?

**Comment by banukutlu** [comment]
> Maybe an example in the readme would help too?

yes good idea, will do

**Review by cdmo — APPROVED** [review]
👌

**Pull request merged**
