### PR TITLE
resolves CSRF vulnerability

### PR DESCRIPTION
**Pull request by Smullz622**
skipping token verification created a cross site request forgery vulnerability

This removes the line that skipped verification

### CODE REVIEW

**Comment by whereismyjetpack** [comment]
we should deploy this and verify that background jobs are working before merging.

**Comment by Smullz622** [comment]
> we should deploy this and verify that background jobs are working before merging.

@whereismyjetpack by deploy, do you mean switch it to a preview branch?

**Comment by ajkiessl** [comment]
I agree with Dann.  We should at least confirm that the polling (`app/javascript/submission_handling/polling.js`) works with CSRF protection turned back on.  We might even want to add a test for it.

**Comment by Smullz622** [comment]
Preview is up https://myaccount-csrf-vuln.dev.k8s.libraries.psu.edu/

It seems like everything is working to me. I was able to place an ILL hold, place/cancel a regular hold, and all the tables were able to correctly retrieve checkout/hold data.

**Review by whereismyjetpack — APPROVED** [review]

**Pull request merged**
