### PR TITLE
updates CI config

### PR DESCRIPTION
**Pull request by whereismyjetpack**
- created an org-global context in circle ci that has "defaulty" values for things like CI_IMAGE_UTILS_IMG_TAG, etc. we're updating the ci-utils image tag to work with the new version of harbor

### CODE REVIEW

**Comment by banukutlu** [comment]
@whereismyjetpack would you mind rebasing so to get the fix that gets the CI to hopefully pass :)

**Review by banukutlu — APPROVED** [review]
lgtm 👍🏻

**Comment by whereismyjetpack** [comment]
still seems like a flake in some place, but it passed.

**Comment by banukutlu** [comment]
> still seems like a flake in some place, but it passed.

yup def. still flakey :/ but yeah this PR looks good, no need to hold the PR up.

**Pull request merged**
